services:
  - type: web
    name: ecommerce-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_TOKEN
        sync: false
      - key: DEV_URL
        sync: false
      - key: PORT
        sync: false